### ISSUE TITLE
URI propertery getter on RequestInformation throws Method not found: 'System.String Std.UriTemplate.Expand(System.String, System.Collections.Generic.Dictionary`2<System.String,System.Object>)

### ISSUE THREAD

**Issue by nschulte-contractor-pepsico** [microsoft/kiota-abstractions-dotnet#170]
Found when calling through Microsoft.Graph .NET SDK:

System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'System.String Std.UriTemplate.Expand(System.String, System.Collections.Generic.Dictionary`2<System.String,System.Object>)'.
  Source=Microsoft.Kiota.Abstractions
  StackTrace:
   at Microsoft.Kiota.Abstractions.RequestInformation.get_URI()
   at Microsoft.Kiota.Abstractions.Authentication.BaseBearerTokenAuthenticationProvider.<AuthenticateRequestAsync>d__7.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.<GetHttpResponseMessage>d__34.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.<SendAsync>d__20`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.ServicePrincipals.ServicePrincipalsRequestBuilder.<GetAsync>d__14.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

**Comment by andrueastman** [comment]
Thanks for raising this. 

This is tracked in  Microsoft.Graph .NET SDK via https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2260 and should be resolved on this repo on the release of https://github.com/microsoft/kiota-abstractions-dotnet/pull/171
